"""add policy and authorization tables

Revision ID: 83252e20ce6c
Revises: f4105445e1ce
Create Date: 2026-09-03 10:32:54.214555

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83252e20ce6c"
down_revision: str | Sequence[str] | None = "f4105445e1ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("autonomous_limit_minor_units", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "autonomous_limit_minor_units >= 0", name="ck_merchant_policies_limit_non_negative"
        ),
        sa.CheckConstraint(
            "char_length(currency) = 3", name="ck_merchant_policies_currency_length"
        ),
        sa.CheckConstraint(
            "currency = upper(currency)", name="ck_merchant_policies_currency_uppercase"
        ),
        sa.CheckConstraint("version > 0", name="ck_merchant_policies_version_positive"),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", name="uq_merchant_policies_merchant"),
    )
    op.create_index(
        op.f("ix_merchant_policies_merchant_id"), "merchant_policies", ["merchant_id"], unique=False
    )
    op.create_table(
        "policy_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("checkout_id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=True),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("autonomous_limit_minor_units", sa.BigInteger(), nullable=False),
        sa.Column("policy_currency", sa.String(length=3), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("amount_minor_units", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('allow', 'require_authorization', 'deny')",
            name="ck_policy_decisions_decision_valid",
        ),
        sa.CheckConstraint(
            "amount_minor_units >= 0", name="ck_policy_decisions_amount_non_negative"
        ),
        sa.CheckConstraint(
            "autonomous_limit_minor_units >= 0", name="ck_policy_decisions_limit_non_negative"
        ),
        sa.CheckConstraint("char_length(currency) = 3", name="ck_policy_decisions_currency_length"),
        sa.CheckConstraint(
            "char_length(policy_currency) = 3", name="ck_policy_decisions_policy_currency_length"
        ),
        sa.CheckConstraint(
            "currency = upper(currency)", name="ck_policy_decisions_currency_uppercase"
        ),
        sa.CheckConstraint(
            "policy_currency = upper(policy_currency)",
            name="ck_policy_decisions_policy_currency_uppercase",
        ),
        sa.CheckConstraint(
            "policy_version >= 0", name="ck_policy_decisions_policy_version_non_negative"
        ),
        sa.ForeignKeyConstraint(["checkout_id"], ["checkouts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["policy_id"], ["merchant_policies.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("checkout_id", name="uq_policy_decisions_checkout"),
    )
    op.create_index(
        op.f("ix_policy_decisions_checkout_id"), "policy_decisions", ["checkout_id"], unique=False
    )
    op.create_index(
        op.f("ix_policy_decisions_merchant_id"), "policy_decisions", ["merchant_id"], unique=False
    )
    op.create_table(
        "checkout_authorizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("checkout_id", sa.UUID(), nullable=False),
        sa.Column("policy_decision_id", sa.UUID(), nullable=False),
        sa.Column("amount_minor_units", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_minor_units >= 0", name="ck_checkout_authorizations_amount_non_negative"
        ),
        sa.CheckConstraint(
            "char_length(currency) = 3", name="ck_checkout_authorizations_currency_length"
        ),
        sa.CheckConstraint(
            "currency = upper(currency)", name="ck_checkout_authorizations_currency_uppercase"
        ),
        sa.ForeignKeyConstraint(["checkout_id"], ["checkouts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["policy_decision_id"], ["policy_decisions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("checkout_id", name="uq_checkout_authorizations_checkout"),
        sa.UniqueConstraint(
            "policy_decision_id", name="uq_checkout_authorizations_policy_decision"
        ),
    )
    op.create_index(
        op.f("ix_checkout_authorizations_checkout_id"),
        "checkout_authorizations",
        ["checkout_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checkout_authorizations_policy_decision_id"),
        "checkout_authorizations",
        ["policy_decision_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_checkout_authorizations_policy_decision_id"), table_name="checkout_authorizations"
    )
    op.drop_index(
        op.f("ix_checkout_authorizations_checkout_id"), table_name="checkout_authorizations"
    )
    op.drop_table("checkout_authorizations")
    op.drop_index(op.f("ix_policy_decisions_merchant_id"), table_name="policy_decisions")
    op.drop_index(op.f("ix_policy_decisions_checkout_id"), table_name="policy_decisions")
    op.drop_table("policy_decisions")
    op.drop_index(op.f("ix_merchant_policies_merchant_id"), table_name="merchant_policies")
    op.drop_table("merchant_policies")
    # ### end Alembic commands ###
