"""create merchants and products tables

Revision ID: c9be56f4f110
Revises:
Create Date: 2026-09-02 14:22:09.561820

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9be56f4f110"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_merchants_name_not_blank"),
        sa.CheckConstraint("length(trim(slug)) > 0", name="ck_merchants_slug_not_blank"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_merchants_slug"), "merchants", ["slug"], unique=True)
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price_minor_units", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(currency) = 3", name="ck_products_currency_length"),
        sa.CheckConstraint("currency = upper(currency)", name="ck_products_currency_uppercase"),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_products_name_not_blank"),
        sa.CheckConstraint("length(trim(sku)) > 0", name="ck_products_sku_not_blank"),
        sa.CheckConstraint("price_minor_units >= 0", name="ck_products_price_non_negative"),
        sa.CheckConstraint("stock_quantity >= 0", name="ck_products_stock_non_negative"),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", "sku", name="uq_products_merchant_sku"),
    )
    op.create_index(
        "ix_products_merchant_active", "products", ["merchant_id", "active"], unique=False
    )
    op.create_index(op.f("ix_products_merchant_id"), "products", ["merchant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_merchant_id"), table_name="products")
    op.drop_index("ix_products_merchant_active", table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_merchants_slug"), table_name="merchants")
    op.drop_table("merchants")
    # ### end Alembic commands ###
