"""add transactions.sequence column

Revision ID: d1e2f3a4b5c6
Revises: c7d4e8f1a6b2
Create Date: 2026-09-04 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1e2f3a4b5c6"
down_revision: str | Sequence[str] | None = "c7d4e8f1a6b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # `GENERATED BY DEFAULT AS IDENTITY` backfills existing rows with
    # sequential values (Postgres assigns them in an unspecified but stable
    # order) and generates new ones for every future insert — the same
    # mechanism `transaction_audit_events.sequence` already uses.
    op.add_column(
        "transactions",
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=False), nullable=False),
    )
    op.create_index(op.f("ix_transactions_sequence"), "transactions", ["sequence"], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_transactions_sequence"), table_name="transactions")
    op.drop_column("transactions", "sequence")
